### ISSUE TITLE
ModuleNotFoundError: No module named 'ddpm.models.unet_openai.unetL'

### ISSUE THREAD

**Issue by earsonlau** [LarsDoorenbos/ccdm-stochastic-segmentation#4]
Hi LD,
        I can't find any code for the class "UNetModelLight" and "UNetModelLightSwin". Maybe you missed?

Error:
File "/home//ccdm-stochastic-segmentation-cityscapes/ddpm/models/unet_openai/__init__.py", line 2, in <module>
    from .unetL import UNetModelLight
ModuleNotFoundError: No module named 'ddpm.models.unet_openai.unetL'

**Comment by TheoPis** [comment]
Hi @earsonlau, thanks for notifying us know of this issue. These modules were not released with the rest of the code because they are not mentioned/used in the paper. They were part of some things we had tested but did ended up not using. We have removed them from the cts branch so the above error should be fixed now.
